from enum import StrEnum


class ErrorCode(StrEnum):
    ANCHOR_NOT_FOUND = "ANCHOR_NOT_FOUND"
    CONTROL_BACKEND_UNSUPPORTED_ROBOT = "CONTROL_BACKEND_UNSUPPORTED_ROBOT"
    EXECUTION_BUNDLE_INCONSISTENT = "EXECUTION_BUNDLE_INCONSISTENT"
    EXECUTION_CANCELLED_BY_USER = "EXECUTION_CANCELLED_BY_USER"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_METADATA_MISSING = "EXECUTION_METADATA_MISSING"
    EXECUTION_PROFILE_INVALID = "EXECUTION_PROFILE_INVALID"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    PERCEPTION_REQUIRED = "PERCEPTION_REQUIRED"
    REGISTRY_INVALID = "REGISTRY_INVALID"
    ROBOT_MODEL_INCOMPATIBLE = "ROBOT_MODEL_INCOMPATIBLE"
    RUNTIME_TIMEOUT = "RUNTIME_TIMEOUT"
    SCENE_FINGERPRINT_MISMATCH = "SCENE_FINGERPRINT_MISMATCH"
    SCENE_INVALID = "SCENE_INVALID"
    TARGET_NOT_FOUND = "TARGET_NOT_FOUND"
    UNSUPPORTED_SKILL = "UNSUPPORTED_SKILL"
